/**
 * BusinessCreation.tsx — Step 4. DSUSA generates Maria's business. She does not author it.
 * Profile, startup budget, revenue model, capital requirement, operating plan, KPIs.
 */
import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useData } from "../data/context.tsx";
import type { BusinessPlan } from "../data/domain.ts";
import { JourneyTracker, SectionTitle, NextStep, money, PagePurpose } from "../components/ui.tsx";

export function BusinessCreation() {
  const data = useData();
  const nav = useNavigate();
  const { entrepreneurId } = useParams();
  const [plan, setPlan] = useState<BusinessPlan | null>(null);
  const [generating, setGenerating] = useState(true);

  useEffect(() => {
    if (!entrepreneurId) return;
    let cancelled = false;
    (async () => {
      // Show DSUSA generating, then reveal the plan.
      await new Promise((r) => setTimeout(r, 1200));
      const p = await data.generateBusinessPlan(entrepreneurId);
      if (!cancelled) { setPlan(p); setGenerating(false); }
    })();
    return () => { cancelled = true; };
  }, [entrepreneurId]);

  if (generating || !plan) {
    return (
      <div className="space-y-6">
        <JourneyTracker current="business_created" />
        <div className="card p-10 text-center">
          <div className="eyebrow text-brand">DSUSA is building the business</div>
          <h1 className="font-display text-2xl font-semibold text-ink mt-2">Generating Maria’s business plan…</h1>
          <div className="mt-6 flex flex-col items-center gap-2 text-sm text-ink-muted">
            {["Business profile", "Startup budget", "Revenue model", "Capital requirements", "Operating plan", "KPIs"].map((s, i) => (
              <span key={s} className="animate-pulse" style={{ animationDelay: `${i * 120}ms` }}>{s} ✓</span>
            ))}
          </div>
        </div>
      </div>
    );
  }

  const startupTotal = plan.startupBudget.reduce((s, b) => s + b.amount, 0);
  const monthlyRevenue = plan.revenueModel.reduce((s, r) => s + r.monthly, 0);

  return (
    <div className="space-y-6">
      <JourneyTracker current="business_created" />
      <div>
        <div className="eyebrow">Business Creation</div>
        <h1 className="font-display text-3xl font-semibold text-ink mt-1">{plan.profile.legalName}</h1>
        <PagePurpose>DSUSA generates the operational foundation for your new business.</PagePurpose>
        <p className="text-ink-muted">Generated by DSUSA · {plan.profile.entityType} · {plan.profile.businessClass}</p>
      </div>

      <div className="grid md:grid-cols-3 gap-4">
        <div className="card p-5">
          <div className="eyebrow">Capital required</div>
          <div className="stat mt-1">{money(plan.capitalRequirement)}</div>
          <div className="text-sm text-ink-muted mt-1">to launch operations</div>
        </div>
        <div className="card p-5">
          <div className="eyebrow">Projected monthly revenue</div>
          <div className="stat mt-1">{money(monthlyRevenue)}</div>
          <div className="text-sm text-ink-muted mt-1">across {plan.revenueModel.length} streams</div>
        </div>
        <div className="card p-5">
          <div className="eyebrow">Startup budget</div>
          <div className="stat mt-1">{money(startupTotal)}</div>
          <div className="text-sm text-ink-muted mt-1">{plan.startupBudget.length} line items</div>
        </div>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <div className="card p-5">
          <SectionTitle>Startup budget</SectionTitle>
          <ul className="divide-y divide-canvas-line">
            {plan.startupBudget.map((b) => (
              <li key={b.item} className="flex justify-between py-2 text-sm">
                <span className="text-ink-soft">{b.item}</span>
                <span className="text-ink font-medium">{money(b.amount)}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="card p-5">
          <SectionTitle>Revenue model</SectionTitle>
          <ul className="divide-y divide-canvas-line">
            {plan.revenueModel.map((r) => (
              <li key={r.stream} className="flex justify-between py-2 text-sm">
                <span className="text-ink-soft">{r.stream}</span>
                <span className="text-ink font-medium">{money(r.monthly)}/mo</span>
              </li>
            ))}
          </ul>
          <SectionTitle>{""}</SectionTitle>
          <div className="eyebrow mt-2">Operating plan</div>
          <ul className="mt-2 space-y-1.5">
            {plan.operatingPlan.map((o) => (
              <li key={o} className="text-sm text-ink-soft flex gap-2"><span className="text-brand">•</span>{o}</li>
            ))}
          </ul>
        </div>
      </div>

      <div className="card p-5">
        <SectionTitle>Business KPIs</SectionTitle>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {plan.kpis.map((k) => (
            <div key={k.name} className="p-4 rounded-lg bg-canvas">
              <div className="text-xs text-ink-muted">{k.name}</div>
              <div className="text-lg font-display font-semibold text-ink mt-0.5">{k.target}</div>
            </div>
          ))}
        </div>
      </div>

      <NextStep
        title="Maria’s business is live"
        body="Her business is created. Next, DSUSA coordinates her funding across the lender, insurance, and compliance partners — so capital is ready before her vehicle is assigned."
        cta={<button className="btn-primary" onClick={() => nav(`/capital/${entrepreneurId}`)}>Continue to capital coordination</button>}
      />
    </div>
  );
}
