/**
 * ReferralImpact.tsx — ecosystem value view for the referral partner.
 * Answer: "Our referrals actually become business owners."
 *
 * Distinct from ReferralDashboard (the operational submit-and-track screen). This is the
 * "why join" impact story a referral org sees.
 */
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { useData } from "../data/context.tsx";
import type { ReferralImpact } from "../data/domain.ts";
import { Stat, SectionTitle, money } from "../components/ui.tsx";
import { StakeholderHeader, ValueTriad, Takeaway } from "../components/stakeholder.tsx";

export function ReferralImpactScreen() {
  const data = useData();
  const { partnerId } = useParams();
  const [d, setD] = useState<ReferralImpact | null>(null);
  useEffect(() => { void data.getReferralImpact(partnerId ?? "defy").then(setD); }, [partnerId]);
  if (!d) return <div className="text-ink-muted">Loading…</div>;

  const funnel: [string, number][] = [
    ["Referred", d.referred],
    ["Qualified", d.qualified],
    ["Businesses created", d.businessesCreated],
    ["Operating", d.operating],
  ];
  const max = d.referred || 1;

  return (
    <div className="space-y-6">
      <StakeholderHeader role="Referral Partner" org={d.partnerName} purpose="Measure the real outcomes created for your community."
        thesis="The people you refer don't disappear into an application. They become qualified, funded, operating business owners — and you can see it." />

      <ValueTriad
        value="Your participants become real business owners with income, not just job placements — economic mobility you can measure."
        opportunities="A turnkey entrepreneurship pathway for the people you serve, with no infrastructure for you to build or run."
        easier="Submit a participant and DSUSA handles qualification, business creation, funding, vehicle, and ongoing support — you watch the outcomes."
      />

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Stat label="Participants referred" value={d.referred} />
        <Stat label="Participants qualified" value={d.qualified} />
        <Stat label="Businesses created" value={d.businessesCreated} />
        <Stat label="Businesses operating" value={d.operating} />
      </div>

      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 card p-5">
          <SectionTitle>Referral → operating funnel</SectionTitle>
          <div className="space-y-3">
            {funnel.map(([label, n]) => (
              <div key={label}>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-ink-soft">{label}</span>
                  <span className="text-ink font-medium">{n}</span>
                </div>
                <div className="h-3 rounded-full bg-canvas overflow-hidden">
                  <div className="h-full bg-brand rounded-full" style={{ width: `${Math.round((n / max) * 100)}%` }} />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <div className="card p-5">
            <div className="eyebrow">Success rate</div>
            <div className="stat text-signal mt-1">{d.successRate}%</div>
            <div className="text-sm text-ink-muted mt-1">referred → operating business</div>
          </div>
          <div className="card p-5">
            <div className="eyebrow">Total community revenue</div>
            <div className="stat mt-1">{money(d.communityRevenue)}</div>
            <div className="text-sm text-ink-muted mt-1">generated by these businesses</div>
          </div>
        </div>
      </div>

      <div className="card p-6 text-center">
        <div className="eyebrow">Estimated economic impact</div>
        <div className="font-display text-4xl font-semibold text-ink mt-1">{money(d.economicImpact)}</div>
        <p className="text-sm text-ink-muted mt-2 max-w-xl mx-auto">
          Business revenue plus downstream effects — wages, taxes, and local spending — generated in your community
          by the entrepreneurs you referred.
        </p>
      </div>

      <div className="card p-6">
        <SectionTitle>Business Continuity</SectionTitle>
        <p className="text-sm text-ink-soft">
          The entrepreneurs you refer receive ongoing operational support intended to help their businesses
          continue operating successfully over time. DSUSA's support is designed not to end at funding or
          launch — it provides infrastructure intended to help businesses remain productive throughout their
          lifecycle, subject to legal, contractual, and operational requirements.
        </p>
      </div>

      <Takeaway>Your referrals actually become business owners — and you can prove the impact.</Takeaway>
    </div>
  );
}
